# This TOML is for adding the "_material" property. See [NOTE] at bottom for details

	ACTION = ["ADD_PROPERTY", "_material", "SPRITE_UNLIT"]

	TARGET_LEVEL_FILES = ["ALL"]
#	TARGET_LEVEL_FILES = ["a02"]

	TARGET_ACTIVE_OBJECT_LAYERS_ONLY    = "true"
	TARGET_OBJECTS_WITH_NAME            = ["AT_ANY"]

	IGNORE_OBJECTS_WITH_PROPERTY        = ["_material"]	# Comment this to disable



#  [NOTE]

# If the object doesn't have the property, property will be added with the specified default value
# Object is IGNORED if it does have the property, with or without any value assigned
#  - I assume no object is having the property but with an empty value
#  - The last Exclusion Rule ignores objects that already has the property, which hopefully makes the tool run faster

# Only objects in active layer, AND is an AT object will be targetted
