TARGET                 = ["z01", "a02"]                     # If first item starts with 'ALL', all levels would be checked

# Currently Available Actions:
#  REMOVE_PROPERTY
#  (more TBA)
ACTION                 = ["REMOVE_PROPERTY", "_material"]

# Inclusion & Exclusion rules
ACTIVE_OBJ_LAYERS_ONLY = "nah"                              # If starts with "true", only active objects would be included
INC_FILTER_OBJ_NAME    = ["door", "AT", "AT_radial"]        # Object names
INC_FILTER_LHS         = ["_sort2"]                         # Properties
EXC_FILTER_LAYER_NAME  = ["objects_breakwall"]              # Objectgroups


